# Generated by Django 3.0.6 on 2020-05-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teste',
            name='id',
        ),
        migrations.AlterField(
            model_name='teste',
            name='teste',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
