# Generated by Django 3.0.6 on 2020-05-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_auto_20200525_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='teste',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
