# Generated by Django 3.0.6 on 2020-05-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_auto_20200527_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='confirmadosFora',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
