# Generated by Django 3.0.6 on 2020-05-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_casos_confirmadosfora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casos',
            name='confirmadosFora',
            field=models.IntegerField(verbose_name='Confirmados fora da cidade'),
        ),
    ]
