# Generated by Django 3.0.6 on 2020-05-25 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casos',
            options={'verbose_name_plural': 'casos'},
        ),
    ]
