# Generated by Django 3.0.6 on 2020-05-25 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_auto_20200525_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teste',
        ),
    ]
