# Generated by Django 3.0.6 on 2020-06-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_auto_20200530_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casos',
            name='confirmadosFora',
        ),
    ]
