# Generated by Django 3.0.7 on 2020-06-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boletim', models.IntegerField()),
                ('tipo', models.CharField(choices=[('confirmado', 'Confirmado'), ('tratamento', 'Em tratamento'), ('internado', 'Internado'), ('recuperado', 'Recuperado'), ('suspeito', 'Suspeito'), ('obito', 'Óbito'), ('descartado', 'Descartado'), ('notificado', 'Notificado')], default='notificado', max_length=15)),
                ('genero', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('outro', 'Outro')], default='feminino', max_length=10)),
                ('faixa', models.CharField(choices=[('0-20', '0-20'), ('20-40', '20-40'), ('40-60', '40-60'), ('60-70', '60-70'), ('70-80', '70-80'), ('80+', '80+')], default='0-20', max_length=5)),
            ],
        ),
    ]
