# Generated by Django 3.0.7 on 2020-06-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicovid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='faixa',
            field=models.CharField(choices=[('0-19', '0-19'), ('20-39', '20-39'), ('40-59', '40-59'), ('60-69', '60-69'), ('70-79', '70-79'), ('80+', '80+')], default='0-19', max_length=5),
        ),
    ]
