# Generated by Django 3.0.7 on 2020-06-29 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicovid', '0002_auto_20200628_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='quantidade',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
