# Generated by Django 3.0.7 on 2020-06-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicovid', '0003_caso_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_habitantes', models.IntegerField()),
            ],
        ),
    ]
