# Generated by Django 3.0.7 on 2020-06-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicovid', '0004_cidade'),
        ('apicovid', '0006_usuario_cidade'),
    ]

    operations = [
    ]
