# Generated by Django 3.0.7 on 2020-07-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicovid', '0008_auto_20200630_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='ativo',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='cidade',
            name='ativo',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
