# Generated by Django 3.0.7 on 2020-07-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicovid', '0016_auto_20200709_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletim',
            name='ativo',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
